/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as DihRouteImport } from './routes/dih'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FREERouteImport } from './routes/FREE'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as DashboardSubsRouteImport } from './routes/dashboard.subs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReferRouteImport } from './routes/dashboard.refer'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard.builder'
import { Route as DashboardBioRouteImport } from './routes/dashboard.bio'
import { Route as DashboardAdsRouteImport } from './routes/dashboard.ads'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as ControlIdRouteImport } from './routes/control.$id'
import { Route as DashboardClientsIdRouteImport } from './routes/dashboard.clients.$id'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments/webhook'
import { Route as ApiPublicBuildserverUploadRouteImport } from './routes/api/public/buildserver/upload'
import { Route as ApiPublicBuildserverStubRouteImport } from './routes/api/public/buildserver/stub'
import { Route as ApiPublicBuildserverStatusRouteImport } from './routes/api/public/buildserver/status'
import { Route as ApiPublicBuildserverProgressRouteImport } from './routes/api/public/buildserver/progress'
import { Route as ApiPublicBuildserverPollRouteImport } from './routes/api/public/buildserver/poll'
import { Route as ApiPublicAgentScreenRouteImport } from './routes/api/public/agent/screen'
import { Route as ApiPublicAgentResultRouteImport } from './routes/api/public/agent/result'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentPollRouteImport } from './routes/api/public/agent/poll'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentCameraRouteImport } from './routes/api/public/agent/camera'
import { Route as ApiPublicAgentAutoRegisterRouteImport } from './routes/api/public/agent/auto-register'
import { Route as ApiPublicBuildsIdDownloadRouteImport } from './routes/api/public/builds/$id.download'
import { Route as ApiPublicAuthDiscordStartRouteImport } from './routes/api/public/auth/discord/start'
import { Route as ApiPublicAuthDiscordCallbackRouteImport } from './routes/api/public/auth/discord/callback'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DihRoute = DihRouteImport.update({
  id: '/dih',
  path: '/dih',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FREERoute = FREERouteImport.update({
  id: '/FREE',
  path: '/FREE',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubsRoute = DashboardSubsRouteImport.update({
  id: '/subs',
  path: '/subs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferRoute = DashboardReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBioRoute = DashboardBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsRoute = DashboardAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ControlIdRoute = ControlIdRouteImport.update({
  id: '/control/$id',
  path: '/control/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientsIdRoute = DashboardClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardClientsRoute,
} as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments/webhook',
    path: '/api/public/nowpayments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildserverUploadRoute =
  ApiPublicBuildserverUploadRouteImport.update({
    id: '/api/public/buildserver/upload',
    path: '/api/public/buildserver/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildserverStubRoute =
  ApiPublicBuildserverStubRouteImport.update({
    id: '/api/public/buildserver/stub',
    path: '/api/public/buildserver/stub',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildserverStatusRoute =
  ApiPublicBuildserverStatusRouteImport.update({
    id: '/api/public/buildserver/status',
    path: '/api/public/buildserver/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildserverProgressRoute =
  ApiPublicBuildserverProgressRouteImport.update({
    id: '/api/public/buildserver/progress',
    path: '/api/public/buildserver/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildserverPollRoute =
  ApiPublicBuildserverPollRouteImport.update({
    id: '/api/public/buildserver/poll',
    path: '/api/public/buildserver/poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentScreenRoute = ApiPublicAgentScreenRouteImport.update({
  id: '/api/public/agent/screen',
  path: '/api/public/agent/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentResultRoute = ApiPublicAgentResultRouteImport.update({
  id: '/api/public/agent/result',
  path: '/api/public/agent/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPollRoute = ApiPublicAgentPollRouteImport.update({
  id: '/api/public/agent/poll',
  path: '/api/public/agent/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCameraRoute = ApiPublicAgentCameraRouteImport.update({
  id: '/api/public/agent/camera',
  path: '/api/public/agent/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAutoRegisterRoute =
  ApiPublicAgentAutoRegisterRouteImport.update({
    id: '/api/public/agent/auto-register',
    path: '/api/public/agent/auto-register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBuildsIdDownloadRoute =
  ApiPublicBuildsIdDownloadRouteImport.update({
    id: '/api/public/builds/$id/download',
    path: '/api/public/builds/$id/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordStartRoute =
  ApiPublicAuthDiscordStartRouteImport.update({
    id: '/api/public/auth/discord/start',
    path: '/api/public/auth/discord/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDiscordCallbackRoute =
  ApiPublicAuthDiscordCallbackRouteImport.update({
    id: '/api/public/auth/discord/callback',
    path: '/api/public/auth/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/FREE': typeof FREERoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dih': typeof DihRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/control/$id': typeof ControlIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/bio': typeof DashboardBioRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subs': typeof DashboardSubsRoute
  '/u/$handle': typeof UHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/api/public/agent/auto-register': typeof ApiPublicAgentAutoRegisterRoute
  '/api/public/agent/camera': typeof ApiPublicAgentCameraRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/agent/screen': typeof ApiPublicAgentScreenRoute
  '/api/public/buildserver/poll': typeof ApiPublicBuildserverPollRoute
  '/api/public/buildserver/progress': typeof ApiPublicBuildserverProgressRoute
  '/api/public/buildserver/status': typeof ApiPublicBuildserverStatusRoute
  '/api/public/buildserver/stub': typeof ApiPublicBuildserverStubRoute
  '/api/public/buildserver/upload': typeof ApiPublicBuildserverUploadRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/builds/$id/download': typeof ApiPublicBuildsIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/FREE': typeof FREERoute
  '/dih': typeof DihRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/control/$id': typeof ControlIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/bio': typeof DashboardBioRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subs': typeof DashboardSubsRoute
  '/u/$handle': typeof UHandleRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/api/public/agent/auto-register': typeof ApiPublicAgentAutoRegisterRoute
  '/api/public/agent/camera': typeof ApiPublicAgentCameraRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/agent/screen': typeof ApiPublicAgentScreenRoute
  '/api/public/buildserver/poll': typeof ApiPublicBuildserverPollRoute
  '/api/public/buildserver/progress': typeof ApiPublicBuildserverProgressRoute
  '/api/public/buildserver/status': typeof ApiPublicBuildserverStatusRoute
  '/api/public/buildserver/stub': typeof ApiPublicBuildserverStubRoute
  '/api/public/buildserver/upload': typeof ApiPublicBuildserverUploadRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/builds/$id/download': typeof ApiPublicBuildsIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/FREE': typeof FREERoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dih': typeof DihRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/control/$id': typeof ControlIdRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/bio': typeof DashboardBioRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/clients': typeof DashboardClientsRouteWithChildren
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/refer': typeof DashboardReferRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subs': typeof DashboardSubsRoute
  '/u/$handle': typeof UHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/clients/$id': typeof DashboardClientsIdRoute
  '/api/public/agent/auto-register': typeof ApiPublicAgentAutoRegisterRoute
  '/api/public/agent/camera': typeof ApiPublicAgentCameraRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/poll': typeof ApiPublicAgentPollRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/result': typeof ApiPublicAgentResultRoute
  '/api/public/agent/screen': typeof ApiPublicAgentScreenRoute
  '/api/public/buildserver/poll': typeof ApiPublicBuildserverPollRoute
  '/api/public/buildserver/progress': typeof ApiPublicBuildserverProgressRoute
  '/api/public/buildserver/status': typeof ApiPublicBuildserverStatusRoute
  '/api/public/buildserver/stub': typeof ApiPublicBuildserverStubRoute
  '/api/public/buildserver/upload': typeof ApiPublicBuildserverUploadRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/auth/discord/callback': typeof ApiPublicAuthDiscordCallbackRoute
  '/api/public/auth/discord/start': typeof ApiPublicAuthDiscordStartRoute
  '/api/public/builds/$id/download': typeof ApiPublicBuildsIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/FREE'
    | '/dashboard'
    | '/dih'
    | '/profile-setup'
    | '/signup'
    | '/status'
    | '/control/$id'
    | '/dashboard/admin'
    | '/dashboard/ads'
    | '/dashboard/bio'
    | '/dashboard/builder'
    | '/dashboard/chat'
    | '/dashboard/clients'
    | '/dashboard/community'
    | '/dashboard/notifications'
    | '/dashboard/refer'
    | '/dashboard/settings'
    | '/dashboard/subs'
    | '/u/$handle'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/api/public/agent/auto-register'
    | '/api/public/agent/camera'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/agent/screen'
    | '/api/public/buildserver/poll'
    | '/api/public/buildserver/progress'
    | '/api/public/buildserver/status'
    | '/api/public/buildserver/stub'
    | '/api/public/buildserver/upload'
    | '/api/public/nowpayments/webhook'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/builds/$id/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/FREE'
    | '/dih'
    | '/profile-setup'
    | '/signup'
    | '/status'
    | '/control/$id'
    | '/dashboard/admin'
    | '/dashboard/ads'
    | '/dashboard/bio'
    | '/dashboard/builder'
    | '/dashboard/chat'
    | '/dashboard/clients'
    | '/dashboard/community'
    | '/dashboard/notifications'
    | '/dashboard/refer'
    | '/dashboard/settings'
    | '/dashboard/subs'
    | '/u/$handle'
    | '/dashboard'
    | '/dashboard/clients/$id'
    | '/api/public/agent/auto-register'
    | '/api/public/agent/camera'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/agent/screen'
    | '/api/public/buildserver/poll'
    | '/api/public/buildserver/progress'
    | '/api/public/buildserver/status'
    | '/api/public/buildserver/stub'
    | '/api/public/buildserver/upload'
    | '/api/public/nowpayments/webhook'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/builds/$id/download'
  id:
    | '__root__'
    | '/'
    | '/FREE'
    | '/dashboard'
    | '/dih'
    | '/profile-setup'
    | '/signup'
    | '/status'
    | '/control/$id'
    | '/dashboard/admin'
    | '/dashboard/ads'
    | '/dashboard/bio'
    | '/dashboard/builder'
    | '/dashboard/chat'
    | '/dashboard/clients'
    | '/dashboard/community'
    | '/dashboard/notifications'
    | '/dashboard/refer'
    | '/dashboard/settings'
    | '/dashboard/subs'
    | '/u/$handle'
    | '/dashboard/'
    | '/dashboard/clients/$id'
    | '/api/public/agent/auto-register'
    | '/api/public/agent/camera'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/poll'
    | '/api/public/agent/register'
    | '/api/public/agent/result'
    | '/api/public/agent/screen'
    | '/api/public/buildserver/poll'
    | '/api/public/buildserver/progress'
    | '/api/public/buildserver/status'
    | '/api/public/buildserver/stub'
    | '/api/public/buildserver/upload'
    | '/api/public/nowpayments/webhook'
    | '/api/public/auth/discord/callback'
    | '/api/public/auth/discord/start'
    | '/api/public/builds/$id/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FREERoute: typeof FREERoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DihRoute: typeof DihRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  ControlIdRoute: typeof ControlIdRoute
  UHandleRoute: typeof UHandleRoute
  ApiPublicAgentAutoRegisterRoute: typeof ApiPublicAgentAutoRegisterRoute
  ApiPublicAgentCameraRoute: typeof ApiPublicAgentCameraRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentPollRoute: typeof ApiPublicAgentPollRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentResultRoute: typeof ApiPublicAgentResultRoute
  ApiPublicAgentScreenRoute: typeof ApiPublicAgentScreenRoute
  ApiPublicBuildserverPollRoute: typeof ApiPublicBuildserverPollRoute
  ApiPublicBuildserverProgressRoute: typeof ApiPublicBuildserverProgressRoute
  ApiPublicBuildserverStatusRoute: typeof ApiPublicBuildserverStatusRoute
  ApiPublicBuildserverStubRoute: typeof ApiPublicBuildserverStubRoute
  ApiPublicBuildserverUploadRoute: typeof ApiPublicBuildserverUploadRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicAuthDiscordCallbackRoute: typeof ApiPublicAuthDiscordCallbackRoute
  ApiPublicAuthDiscordStartRoute: typeof ApiPublicAuthDiscordStartRoute
  ApiPublicBuildsIdDownloadRoute: typeof ApiPublicBuildsIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dih': {
      id: '/dih'
      path: '/dih'
      fullPath: '/dih'
      preLoaderRoute: typeof DihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FREE': {
      id: '/FREE'
      path: '/FREE'
      fullPath: '/FREE'
      preLoaderRoute: typeof FREERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subs': {
      id: '/dashboard/subs'
      path: '/subs'
      fullPath: '/dashboard/subs'
      preLoaderRoute: typeof DashboardSubsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/refer': {
      id: '/dashboard/refer'
      path: '/refer'
      fullPath: '/dashboard/refer'
      preLoaderRoute: typeof DashboardReferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bio': {
      id: '/dashboard/bio'
      path: '/bio'
      fullPath: '/dashboard/bio'
      preLoaderRoute: typeof DashboardBioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads': {
      id: '/dashboard/ads'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/control/$id': {
      id: '/control/$id'
      path: '/control/$id'
      fullPath: '/control/$id'
      preLoaderRoute: typeof ControlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clients/$id': {
      id: '/dashboard/clients/$id'
      path: '/$id'
      fullPath: '/dashboard/clients/$id'
      preLoaderRoute: typeof DashboardClientsIdRouteImport
      parentRoute: typeof DashboardClientsRoute
    }
    '/api/public/nowpayments/webhook': {
      id: '/api/public/nowpayments/webhook'
      path: '/api/public/nowpayments/webhook'
      fullPath: '/api/public/nowpayments/webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buildserver/upload': {
      id: '/api/public/buildserver/upload'
      path: '/api/public/buildserver/upload'
      fullPath: '/api/public/buildserver/upload'
      preLoaderRoute: typeof ApiPublicBuildserverUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buildserver/stub': {
      id: '/api/public/buildserver/stub'
      path: '/api/public/buildserver/stub'
      fullPath: '/api/public/buildserver/stub'
      preLoaderRoute: typeof ApiPublicBuildserverStubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buildserver/status': {
      id: '/api/public/buildserver/status'
      path: '/api/public/buildserver/status'
      fullPath: '/api/public/buildserver/status'
      preLoaderRoute: typeof ApiPublicBuildserverStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buildserver/progress': {
      id: '/api/public/buildserver/progress'
      path: '/api/public/buildserver/progress'
      fullPath: '/api/public/buildserver/progress'
      preLoaderRoute: typeof ApiPublicBuildserverProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buildserver/poll': {
      id: '/api/public/buildserver/poll'
      path: '/api/public/buildserver/poll'
      fullPath: '/api/public/buildserver/poll'
      preLoaderRoute: typeof ApiPublicBuildserverPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/screen': {
      id: '/api/public/agent/screen'
      path: '/api/public/agent/screen'
      fullPath: '/api/public/agent/screen'
      preLoaderRoute: typeof ApiPublicAgentScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/result': {
      id: '/api/public/agent/result'
      path: '/api/public/agent/result'
      fullPath: '/api/public/agent/result'
      preLoaderRoute: typeof ApiPublicAgentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/poll': {
      id: '/api/public/agent/poll'
      path: '/api/public/agent/poll'
      fullPath: '/api/public/agent/poll'
      preLoaderRoute: typeof ApiPublicAgentPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/camera': {
      id: '/api/public/agent/camera'
      path: '/api/public/agent/camera'
      fullPath: '/api/public/agent/camera'
      preLoaderRoute: typeof ApiPublicAgentCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/auto-register': {
      id: '/api/public/agent/auto-register'
      path: '/api/public/agent/auto-register'
      fullPath: '/api/public/agent/auto-register'
      preLoaderRoute: typeof ApiPublicAgentAutoRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/builds/$id/download': {
      id: '/api/public/builds/$id/download'
      path: '/api/public/builds/$id/download'
      fullPath: '/api/public/builds/$id/download'
      preLoaderRoute: typeof ApiPublicBuildsIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/start': {
      id: '/api/public/auth/discord/start'
      path: '/api/public/auth/discord/start'
      fullPath: '/api/public/auth/discord/start'
      preLoaderRoute: typeof ApiPublicAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/discord/callback': {
      id: '/api/public/auth/discord/callback'
      path: '/api/public/auth/discord/callback'
      fullPath: '/api/public/auth/discord/callback'
      preLoaderRoute: typeof ApiPublicAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardClientsRouteChildren {
  DashboardClientsIdRoute: typeof DashboardClientsIdRoute
}

const DashboardClientsRouteChildren: DashboardClientsRouteChildren = {
  DashboardClientsIdRoute: DashboardClientsIdRoute,
}

const DashboardClientsRouteWithChildren =
  DashboardClientsRoute._addFileChildren(DashboardClientsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAdsRoute: typeof DashboardAdsRoute
  DashboardBioRoute: typeof DashboardBioRoute
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardClientsRoute: typeof DashboardClientsRouteWithChildren
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReferRoute: typeof DashboardReferRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubsRoute: typeof DashboardSubsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAdsRoute: DashboardAdsRoute,
  DashboardBioRoute: DashboardBioRoute,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardClientsRoute: DashboardClientsRouteWithChildren,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReferRoute: DashboardReferRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubsRoute: DashboardSubsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FREERoute: FREERoute,
  DashboardRoute: DashboardRouteWithChildren,
  DihRoute: DihRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  ControlIdRoute: ControlIdRoute,
  UHandleRoute: UHandleRoute,
  ApiPublicAgentAutoRegisterRoute: ApiPublicAgentAutoRegisterRoute,
  ApiPublicAgentCameraRoute: ApiPublicAgentCameraRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentPollRoute: ApiPublicAgentPollRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentResultRoute: ApiPublicAgentResultRoute,
  ApiPublicAgentScreenRoute: ApiPublicAgentScreenRoute,
  ApiPublicBuildserverPollRoute: ApiPublicBuildserverPollRoute,
  ApiPublicBuildserverProgressRoute: ApiPublicBuildserverProgressRoute,
  ApiPublicBuildserverStatusRoute: ApiPublicBuildserverStatusRoute,
  ApiPublicBuildserverStubRoute: ApiPublicBuildserverStubRoute,
  ApiPublicBuildserverUploadRoute: ApiPublicBuildserverUploadRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicAuthDiscordCallbackRoute: ApiPublicAuthDiscordCallbackRoute,
  ApiPublicAuthDiscordStartRoute: ApiPublicAuthDiscordStartRoute,
  ApiPublicBuildsIdDownloadRoute: ApiPublicBuildsIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
